# Generated by Django 4.0.1 on 2022-02-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('constituency_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('constituency_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('county_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('ward_name', models.CharField(max_length=200)),
                ('constituency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('photo', models.ImageField(default='car_placeholder.png', upload_to='')),
                ('disability', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('ward_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.ward')),
            ],
        ),
        migrations.AddField(
            model_name='constituency',
            name='county_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.county'),
        ),
    ]
