# Generated by Django 4.0.1 on 2022-03-08 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('constituency_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('constituency_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_code', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('county_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('ward_name', models.CharField(max_length=200)),
                ('constituency_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id_serial_number', models.CharField(default=None, max_length=8)),
                ('email', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('photo', models.ImageField(default='car_placeholder.png', upload_to='')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('ward_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.ward')),
            ],
        ),
        migrations.AddField(
            model_name='constituency',
            name='county_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vote.county'),
        ),
    ]
