# Generated by Django 4.0.1 on 2022-02-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
