# Generated by Django 4.0.1 on 2022-03-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='id_serial_number',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
