# Generated by Django 4.0.1 on 2022-04-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='county_code',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='id_serial_number',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='voter',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
