# Generated by Django 4.0.1 on 2022-03-05 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0002_alter_voter_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constituency',
            old_name='constituency_id',
            new_name='constituency_code',
        ),
        migrations.RenameField(
            model_name='constituency',
            old_name='county_id',
            new_name='county_code',
        ),
        migrations.RenameField(
            model_name='county',
            old_name='county_id',
            new_name='county_code',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='ward_id',
            new_name='ward_code',
        ),
        migrations.RenameField(
            model_name='ward',
            old_name='constituency_id',
            new_name='constituency_code',
        ),
        migrations.RenameField(
            model_name='ward',
            old_name='ward_id',
            new_name='ward_code',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='id',
        ),
        migrations.AddField(
            model_name='voter',
            name='email',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voter',
            name='id_serial_number',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
