# Generated by Django 4.0.1 on 2022-04-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_county_county_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='county_code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
