# Generated by Django 4.0.1 on 2022-04-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_county_county_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='photo',
            field=models.ImageField(default='user.svg', upload_to='media'),
        ),
    ]
