# Generated by Django 4.0.1 on 2022-03-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_rename_constituency_id_constituency_constituency_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='county_code',
            field=models.TextField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
