# Generated by Django 4.0.1 on 2022-03-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_county_county_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='county_code',
            field=models.TextField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
